### ISSUE TITLE
Ime repozitorija

### ISSUE THREAD

**Issue by jaanos** [BlackPhoenixSlo/Matching-with-low-crossing-number#1]
@BlackPhoenixSlo, svetujem, da ima repozitorij bolj pomenljivo ime, npr. `Matching-with-low-crossing-number`. Ime spremeniš tako, da zgoraj klikneš na *Settings*, nato pa spremeniš ime pod **Repository name**. Seveda poskrbi tudi za ustrezen naslov naloge in številko skupine na wikiju na spletni učilnici.

**Comment by BlackPhoenixSlo** [comment]
Se oproščam za napako, Sem spremenil številko v 19 in spremenil naslov projektne naloge. A lahko preverite, če je naloga korektno pripravljena? Seveda imam namen še enkrat prebrat in popravit pisne napake čez par dni ko pozabim kaj sem pisal.

Lep pozdrav, Jaka

**Comment by jaanos** [comment]
Številko skupine si popravil, naslov naloge na wikiju pa je še vedno isti kot pri prejšnji skupini.

Kolikor vidim, je tvoja metoda taka, da pregledaš čisto vse permutacije točk - kot sam vidiš, je to IZJEMNO neučinkovito, saj pregledaš ne samo eksponentno mnogo rešitev, pač pa vsako (ekvivalentno) rešitev eksponentno mnogo krat. Algoritem, ki ga dobiš s celoštevilskim linearnim programiranjem, bi seveda prav tako moral teči v eksponentnem času, a bi vendarle moral biti precej hitrejši, saj poskusi knjižnica za reševanje CLP čim bolj omejiti iskalni prostor.

Celoštevilski linearni program, ki ga imaš zapisanega v poročilu, ni popolnoma ustrezen - iščeš namreč maksimum (?) vsote vrednosti *y*<sub>*ijkm*</sub>, ki so definirane kot konstante (vrednosti *x*<sub>*uv*</sub> so tako povsem irelevantne). Prav tako ni jasno, zakaj imaš *k, m* pod max - ciljna funkcija je namreč samo ena. Zadostovalo bo, če za vsako daljico *uv* poiščeš število presečišč s premicami (to lahko narediš v času *O*(*n*<sup>4</sup>) - seveda lahko tukaj izpustiš vse premice skozi *u* ali *v*) in s CLP potem poiščeš tako prirejanje, ki bo prineslo čim manjše število presečišč (tj., števila presečišč uporabiš kot koeficiente v ciljni funkciji).

V poročilu praviš, da si za vsako število točk naredil 3 ponovitve - to je sicer sprejemljivo v primerih, ko je računanje dolgotrajno, sicer pa bo bolje narediti čim več ponovitev (raje 1000 kot 100, če je to seveda časovno smiselno - morda lahko pri večjih *n* zmanjšaš število ponovitev, da ti bo zneslo). Če boš za kakšen izračun na CoCalcu potreboval več časa (zastojnska različica namreč prekine izvajanje po 30 minutah neaktivnosti), lahko jaz poženem na strežniku, kjer lahko program teče tudi več dni - v tem primeru mi sporoči, kaj točno naj poženem (najbolje, da je koda organizirana tako, da lahko poženem en sam klic funkcije).

Samo poročilo je težko brati (slovnične in tipkarske napake, različne pisave, uporaba angleške terminologije). Svetoval bi, da poročilo raje pripraviš v LaTeXu - vsekakor pa poskrbi za izvoz v PDF, saj prikaz Wordovih dokumentov na različnih sistemih ni konsistenten. Iz grafov velikokrat ni mogoče razbrati veliko, saj je mogoče podatke ločiti od 0 le pri največjih vrednostih na osi x - če imaš take podatke, si lahko pomagaš z logaritemsko lestvico na osi y. Trdiš tudi, da je časovna zahtevnost kubična v *n*, kar pa očitno ni res (kvečjemu je to res za obravnavo ene permutacije), prav tako naj bi se število presečišč zmanjševalo, česar ni mogoče sklepati iz grafa (pričakoval bi seveda, da bo število rastlo korensko v *n*).

**Comment by BlackPhoenixSlo** [comment]
Razumem, program ni napisan v CLP. Zaradi tega so takšne napake. Res potrebujem to narest, čeprav sem zmanjšal število permutacij z 2^n ni bilo dovolj. 

Ševedno mi ni jasno kako spisat CLP program. Poiskal sem daljice in sestel vse možne preseke daljic vsemi poljubnimi premicami. 
Bi se lahko enkrat dobila, da mi razložiš?

**Comment by jaanos** [comment]
Lahko se slišiva jutri (petek) ob 11:30. Prosim sporoči, če ti ustreza.

**Comment by BlackPhoenixSlo** [comment]
Lahko, preko zooma?

**Comment by BlackPhoenixSlo** [comment]
Sem dokončal, je možno pognati metodo (2022-01-07-114846.ipynb) na šolskem serverju?
